# Generated by Django 3.2.6 on 2026-05-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nit'], name='empresas_em_nit_ac5873_idx'),
        ),
    ]
