# Generated by Django 3.2.6 on 2026-05-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCostoCrudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=10)),
                ('servicio', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(max_length=7)),
                ('cpu_avg', models.FloatField(default=0.0)),
                ('netout_gb', models.FloatField(default=0.0)),
                ('costo', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
            ],
        ),
        migrations.AddIndex(
            model_name='registrocostocrudo',
            index=models.Index(fields=['empresa', 'periodo'], name='extractor_r_empresa_31dce3_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocostocrudo',
            index=models.Index(fields=['periodo'], name='extractor_r_periodo_d19487_idx'),
        ),
    ]
